### ISSUE TITLE
Empty EXIF data

### ISSUE THREAD

**Issue by jonasjohansson** [Carnaux/NFT-Marker-Creator#15]
Using the Pinball example, which clearly has EXIF data, I receive this message: "The EXIF info of this image is empty or it does not exist. Do you want to inform its properties manually?[y/n]"

<img width="246" alt="Screenshot 2019-12-18 at 17 51 58" src="https://user-images.githubusercontent.com/557050/71106178-23202200-21bf-11ea-9c30-f50b6bbd350c.png">

Any thoughts on why this is? The file has read rights.

**Comment by kalwalt** [comment]
@jonasjohansson this is a good question! Thanks to note this, maybe the code require some specific EXIF data? or the EXIF data in pinball image is not well formed? just thinking...

**Comment by Carnaux** [comment]
Maybe it doesn't have any relevant information for the decoder, from the print, looks like it is just camera info, and the code doesn't return an error, it returns an empty object.

**Comment by jonasjohansson** [comment]
Well, the first thing it does ask for when entering manually is the Width and Height, which does exist in the EXIF data. The second question from the Terminal script is the DPI, which I am quite positive also does exist in the EXIF data.

Otherwise, what EXIF data is of any value? Why even request it?

**Comment by jonasjohansson** [comment]
<img width="697" alt="Screenshot 2019-12-19 at 21 20 01" src="https://user-images.githubusercontent.com/557050/71206647-576e0e00-22a5-11ea-8f2e-2a5efe0441b2.png">

**Comment by Carnaux** [comment]
It asks for typing the info only if it doesnt find the tags I hard-coded it to look for, or if the EXIF object returns empty, but because the same info can be in different tags, and exist at the same time, some info may not be used, even if you know that they can work, for exemple, the color space can have 3 different tags that basically mean the same thing, in the case of the setting the number of channels. Not all jpegs have the same EXIF or the same content. I will update with the "dimensions" tag. And is already planned to add a second jpeg EXIF reader for catching what the first one missed.

**Comment by kalwalt** [comment]
@jonasjohansson can you post the image if it is possible? i would test it.

**Comment by jonasjohansson** [comment]
It is the default pinball image included in the repo!

**Comment by jonasjohansson** [comment]
@Carnaux I suppose me raising the issue is due to the pinball example being the file that comes with the repo. If it was any other file, one that I would have produced myself, I wouldn't have reacted as much, but it would be cool to understand in what way the EXIF data should be applied to be read by the reader.
