### ISSUE TITLE
Images with transparency

### ISSUE THREAD

**Issue by Carnaux** [Carnaux/NFT-Marker-Creator#41]
@kalwalt @nicolocarpignoli @ThorstenBux did any of you tested images with transparency? I believe they get lower confidence levels because of the 0 alpha values.

**Comment by kalwalt** [comment]
No i never did before. I think because you track always opaque images has sense to delete transparency, or remove the alpha channel, probably that can be done via code too.

**Comment by Carnaux** [comment]
Yeah, the code converts RGBA to RGB, so it transforms the opacity to opaque, but I got to a use case that the image has a transparent background. What do you think about it? If I convert that background to white or black it can heavily interfere with the generation and tracking.

**Comment by kalwalt** [comment]
>  If I convert that background to white or black it can heavily interfere with the generation and tracking.

This is sure. At least a message in the console that alert the image has transparency asking if you want to procede, and if yes if you want to add a white or black layer ( or gray?). I think this is the smarter idea for now. I always used opaque images for NFT, because are the better, but if someone has a transparent one i think it is a good idea to let the user choice what to do.
